name: NodeJS

on:
  push:
    branches: [main]
  pull_request:

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: stellar/actions/rust-cache@main
    - run: rustup update
    - run: rustup target add wasm32-unknown-unknown
    - run: rustup target add x86_64-unknown-linux-gnu
    - run: rustup toolchain install nightly
    - run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - run: cargo fmt --all --check
    - run: cargo install --locked --version 0.1.2 soroban-cli
    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: 17.x
        cache: 'npm'
    - run: npm ci
    - run: npm run-script setup
    - run: npm run-script build
